# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import VehicleServer_pb2 as VehicleServer__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in VehicleServer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPropertyConfig = channel.unary_stream(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/GetAllPropertyConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehiclePropConfig.FromString,
                _registered_method=True)
        self.SetValues = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/SetValues',
                request_serializer=VehicleServer__pb2.VehiclePropValueRequests.SerializeToString,
                response_deserializer=VehicleServer__pb2.SetValueResults.FromString,
                _registered_method=True)
        self.GetValues = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/GetValues',
                request_serializer=VehicleServer__pb2.VehiclePropValueRequests.SerializeToString,
                response_deserializer=VehicleServer__pb2.GetValueResults.FromString,
                _registered_method=True)
        self.UpdateSampleRate = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/UpdateSampleRate',
                request_serializer=VehicleServer__pb2.UpdateSampleRateRequest.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehicleHalCallStatus.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/CheckHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehicleHalCallStatus.FromString,
                _registered_method=True)
        self.Dump = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/Dump',
                request_serializer=VehicleServer__pb2.DumpOptions.SerializeToString,
                response_deserializer=VehicleServer__pb2.DumpResult.FromString,
                _registered_method=True)
        self.StartPropertyValuesStream = channel.unary_stream(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/StartPropertyValuesStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehiclePropValues.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/Subscribe',
                request_serializer=VehicleServer__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehicleHalCallStatus.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/android.hardware.automotive.vehicle.proto.VehicleServer/Unsubscribe',
                request_serializer=VehicleServer__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=VehicleServer__pb2.VehicleHalCallStatus.FromString,
                _registered_method=True)


class VehicleServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPropertyConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSampleRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPropertyValuesStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPropertyConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllPropertyConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=VehicleServer__pb2.VehiclePropConfig.SerializeToString,
            ),
            'SetValues': grpc.unary_unary_rpc_method_handler(
                    servicer.SetValues,
                    request_deserializer=VehicleServer__pb2.VehiclePropValueRequests.FromString,
                    response_serializer=VehicleServer__pb2.SetValueResults.SerializeToString,
            ),
            'GetValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValues,
                    request_deserializer=VehicleServer__pb2.VehiclePropValueRequests.FromString,
                    response_serializer=VehicleServer__pb2.GetValueResults.SerializeToString,
            ),
            'UpdateSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSampleRate,
                    request_deserializer=VehicleServer__pb2.UpdateSampleRateRequest.FromString,
                    response_serializer=VehicleServer__pb2.VehicleHalCallStatus.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=VehicleServer__pb2.VehicleHalCallStatus.SerializeToString,
            ),
            'Dump': grpc.unary_unary_rpc_method_handler(
                    servicer.Dump,
                    request_deserializer=VehicleServer__pb2.DumpOptions.FromString,
                    response_serializer=VehicleServer__pb2.DumpResult.SerializeToString,
            ),
            'StartPropertyValuesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StartPropertyValuesStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=VehicleServer__pb2.VehiclePropValues.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=VehicleServer__pb2.SubscribeRequest.FromString,
                    response_serializer=VehicleServer__pb2.VehicleHalCallStatus.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=VehicleServer__pb2.UnsubscribeRequest.FromString,
                    response_serializer=VehicleServer__pb2.VehicleHalCallStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'android.hardware.automotive.vehicle.proto.VehicleServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('android.hardware.automotive.vehicle.proto.VehicleServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPropertyConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/GetAllPropertyConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            VehicleServer__pb2.VehiclePropConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/SetValues',
            VehicleServer__pb2.VehiclePropValueRequests.SerializeToString,
            VehicleServer__pb2.SetValueResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/GetValues',
            VehicleServer__pb2.VehiclePropValueRequests.SerializeToString,
            VehicleServer__pb2.GetValueResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/UpdateSampleRate',
            VehicleServer__pb2.UpdateSampleRateRequest.SerializeToString,
            VehicleServer__pb2.VehicleHalCallStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/CheckHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            VehicleServer__pb2.VehicleHalCallStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/Dump',
            VehicleServer__pb2.DumpOptions.SerializeToString,
            VehicleServer__pb2.DumpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPropertyValuesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/StartPropertyValuesStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            VehicleServer__pb2.VehiclePropValues.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/Subscribe',
            VehicleServer__pb2.SubscribeRequest.SerializeToString,
            VehicleServer__pb2.VehicleHalCallStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/android.hardware.automotive.vehicle.proto.VehicleServer/Unsubscribe',
            VehicleServer__pb2.UnsubscribeRequest.SerializeToString,
            VehicleServer__pb2.VehicleHalCallStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
